import {
  AlertTriangle,
  ArrowRight,
  Ban,
  Building2,
  Check,
  Columns3,
  Copy,
  Download,
  ExternalLink,
  FileText,
  Filter,
  GitCommitHorizontal,
  LayoutDashboard,
  Link as LinkIcon,
  LoaderCircle,
  MessageCircle,
  Network,
  Paperclip,
  Plus,
  RotateCcw,
  Save,
  Search,
  Send,
  SquarePen,
  Trash2,
  Upload,
  UserPlus,
  UsersRound,
  X,
  type LucideIcon,
} from "lucide-react";

const iconMap = {
  "layout-dashboard": LayoutDashboard,
  "git-commit-horizontal": GitCommitHorizontal,
  "users-round": UsersRound,
  network: Network,
  "columns-3": Columns3,
  "building-2": Building2,
  "alert-triangle": AlertTriangle,
  link: LinkIcon,
  search: Search,
  "square-pen": SquarePen,
  plus: Plus,
  download: Download,
  "user-plus": UserPlus,
  filter: Filter,
  "arrow-right": ArrowRight,
  copy: Copy,
  "trash-2": Trash2,
  save: Save,
  "rotate-ccw": RotateCcw,
  "message-circle": MessageCircle,
  x: X,
  send: Send,
  "loader-circle": LoaderCircle,
  check: Check,
  ban: Ban,
  "external-link": ExternalLink,
  "file-text": FileText,
  paperclip: Paperclip,
  upload: Upload,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof iconMap;

export function Icon({ name, className }: { name: IconName; className?: string }) {
  const Component = iconMap[name];
  return <Component className={className} aria-hidden="true" />;
}
